### PR TITLE
fix #77: B=1 considered baffling to Windows

### LINKED ISSUE #77: B=1 considered baffling to Windows
The problem: We want to know when a package.json run script is ours to update at will without undoing deliberate changes made by people working on the service. 

The solution: Prefix our scripts with a `B=1` to set a most-likely-harmless env var. If we see this prefix on an update run, we manage that run script. If this string is missing, we leave the run script alone.

The problem caused by the solution: `B=1` is not interpretable by Windows PowerShell and causes any invocation of a runscript with it to fail. (It seems fine in PowerShell on Mac. ?? )

We could use [cross-env](https://github.com/kentcdodds/cross-env) to continue setting an env var, but the point of decorating the run scripts isn't setting an env var; it's decorating the run-scripts so we can decide if we can edit them. It feels a little silly to add an entire unused dep for this.

We could find another no-op prelude to the runscripts, one that works cross-platform. `echo &&` might work.

Or we could always update every run script we know about that starts with `boltzman:` and leave anything else alone if present. This is predictable behavior, at least.

### PR DESCRIPTION
**Pull request by ceejbot**
We now track run scripts through versions of Boltzmann. If a standard run
script target (one not prefixed with `boltzmann:`) if already set, we compare
it to our past history of values for that run script to decide if we're
managing it.

`runscripts.ron` now records my best understanding of the history of our run
scripts. We've only really changed two of them over time, as far as I can tell.

Took this opportunity to improve output a little bit. We now tell you if you're
upgrading an installation by comparing the previous version with the one you're
applying.

### CODE REVIEW

File: src/main.rs [hunk 1]
```diff
@@ -127,11 +132,18 @@ pub struct Flags {
...
+    version: Version,
+    value: String,
+}
+
 #[derive(Deserialize)]
 struct RunScriptSpec {
     key: String,
     value: String,
     preconditions: Option<When>,
+    versions: Vec<VersionedScript>,
```
Comment (chrisdickinson) [inline src/main.rs:147]: If you add `#[serde(default)]` here, you won't have to include `versions: []` where no versioning applies!

File: src/main.rs [hunk 2]
```diff
@@ -337,7 +351,17 @@ fn main() -> std::result::Result<(), Box<dyn std::error::Error + 'static>> {
     let mut package_json = if let Some(mut package_json) =
         load_package_json(&flags, default_settings.clone())
     {
-        info!("    loaded settings from existing package.json");
+        if let Some(t) = package_json.boltzmann.clone() {
+            let parsed = Version::parse(&t.version.unwrap_or_else(|| "0.0.0".to_string()));
+            if let Ok(p) = parsed {
+                prev_version = p;
+            }
+        }
```
Comment (chrisdickinson) [inline src/main.rs:357]: _gestures grandly at this green space_ what a good place to golf

File: src/main.rs [hunk 3]
```diff
@@ -487,32 +515,55 @@ fn main() -> std::result::Result<(), Box<dyn std::error::Error + 'static>> {
...
+                    // targets like `test` and `postinstall`. If they're present and set to a value we
+                    // previously gave them, we can feel free to update them. If not, we move on.
+                    if candidate.versions.is_empty() {
+                        debug!( "{} has no history", format!("npm run {}", candidate.key).bold().red());
                         continue 'next;
                     }
+
+                    // First, find the previous-in-semver-order version in our list of versions.
+                    // This is the version our runscript would have come from. If a match, we want to update.
+                    // If not a match, we continue with the next script candidate.
```
Comment (chrisdickinson) [inline src/main.rs:531]: Interesting – I would've thought we'd do something like "load version of source; lookup runscript at source version from a hash of version=>script value, if they match, update to latest"? (That should, _in theory_, remove the need to sort versions, at least)

File: src/main.rs (hunk 1 above)
Comment (ceejbot) [reply src/main.rs:147]: ooooooooooooh love this

File: src/main.rs (hunk 3 above)
Comment (ceejbot) [reply src/main.rs:531]: Well, the map is pretty sparse-- we only ever changed two run scripts over time really. I was a little surprised by this. So I thought it was easier to record when we initially set something, and when it changed, and just walk back.
